# -*- coding: utf-8 -*-
"""Dialogue-Data-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccgvnYg1qT7Y8YzEJ_UnHxqVJDkeOqlZ

We will be using the DailyDialog dataset (http://yanran.li/dailydialog)

Download the Dataset:
"""

!pip install datasets

"""Load the dataset directly from Hugging Face:"""

from datasets import load_dataset

# Load DailyDialog dataset
dataset = load_dataset("daily_dialog")

"""Explore the Dataset"""

# Check the dataset
print(dataset)

# Show some examples
for i in range(5):
    print(dataset['train'][i])

"""Preprocess the Data

convert it into a pandas DataFrame and analyze data
"""

import pandas as pd

# Convert to DataFrame
df = pd.DataFrame(dataset['train'])

# Show the DataFrame
print(df.head())
print('--------------------')
# total number of dialogues:
print(f'Total dialogues: {len(df)}')

"""Data Cleaning"""

# lean the dialogues by joining the conversation turns into a single string and converting the data into a more manageable format.

# Remove any unnecessary spaces and join the dialogue lists into a single string
df['dialog'] = df['dialog'].apply(lambda x: ' '.join(x).replace('  ', ' '))

# Show the cleaned DataFrame
print(df[['dialog', 'act', 'emotion']].head())

"""Exploratory Data Analysis (EDA)"""

# Check unique emotions
unique_emotions = set()
df['emotion'].apply(lambda x: unique_emotions.update(x.split(', ')))
print(f'Unique emotions: {unique_emotions}')

# Count occurrences of each emotion
emotion_counts = df['emotion'].value_counts()
print(emotion_counts)

"""Visualization (Optional)"""

import matplotlib.pyplot as plt
import seaborn as sns

# Plot the top 10 emotions
top_emotions = emotion_counts.head(10)
sns.barplot(x=top_emotions.values, y=top_emotions.index)
plt.title('Top 10 Emotions in DailyDialog')
plt.xlabel('Count')
plt.ylabel('Emotion')
plt.show()

"""Save the Preprocessed Data (if needed)

"""

df.to_csv('cleaned_dailydialog.csv', index=False)

# Convert emotion sequences into individual rows
exploded_emotions = df['emotion'].explode()